name: Ubuntu

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cpp_compiler: [g++, clang++]
        include:
          - cpp_compiler: g++
            c_compiler: gcc
          - cpp_compiler: clang++
            c_compiler: clang

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: sudo pip3 install conan

    - name: Install dependencies
      run: sed 's/\r$//' apt_packages.txt | sed 's/#.*//' | xargs sudo apt-get install -y

    - name: Configure
      run: CC=${{ matrix.c_compiler }} CXX=${{ matrix.cpp_compiler }} cmake -G"Unix Makefiles" -Bbuild

    - name: Build
      run: cmake --build build
