name: Ubuntu

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sed 's/\r$//' requirements.txt | sed 's/#.*//' | xargs sudo apt-get install -y

    - name: Build
      run: |
        mkdir build && cd build
        cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -G"Unix Makefiles" .. && make
