name: Ubuntu

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sed 's/\r$//' requirements.txt | sed 's/#.*//' | xargs sudo apt-get install -y

    - name: Build
      run: |
        mkdir build && cd build
        cmake -G"Unix Makefiles" .. && make
